### ISSUE TITLE
POST to /refreshIdToken

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/kong#36]
results in ```http://localhost:8080/authorize?scope=openid%20email%20phone%20userInfo%20roles&client_id=oidcCLIENT&response_type=code&state=cd0e74d45deb10d6556f60aad5ceaa4d&nonce=a8f76e7de751385b4b3595527be314d2&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fcallback&prompt=none```

**Comment by kwierchris** [comment]
Is this correct?

**Comment by sureshvarman-cronj** [comment]
Yeah, this is fine, happens in background.
